name: 'Check spelling'
description: 'Spell check commits'
author: 'jsoref'
branding:
  icon: 'edit-3'
  color: 'red'
inputs:
  GITHUB_TOKEN:
    description: 'The GITHUB_TOKEN secret'
    default: "${{ github.token }}"
    required: true
  bucket:
    description: 'Container for spelling configuration'
  project:
    description: 'Folder/Branch within bucket containing spelling configuration'
  config:
    description: 'Spelling configuration directory'
    default: ".github/actions/spelling"

  debug:
    description: 'Debug'
runs:
  using: 'node12'
  main: 'trampoline.js'
